// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline bool FunctionPointer_GameAgent_CheckWinCondition(Agent* self) { return (bool)((GameAgent*)self)->_Execute_Method_<METHOD_TYPE_GameAgent_CheckWinCondition, bool >(); }
	inline void FunctionPointer_GameAgent_DayPhase(Agent* self) { ((GameAgent*)self)->_Execute_Method_<METHOD_TYPE_GameAgent_DayPhase, void >(); }
	inline void FunctionPointer_GameAgent_LogMessage(char* param0) { GameAgent::LogMessage(param0); }
	inline void FunctionPointer_GameAgent_NightPhase(Agent* self) { ((GameAgent*)self)->_Execute_Method_<METHOD_TYPE_GameAgent_NightPhase, void >(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
