// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct METHOD_TYPE_GameAgent_CheckWinCondition { };
template<> inline bool GameAgent::_Execute_Method_<METHOD_TYPE_GameAgent_CheckWinCondition>()
{
	return this->GameAgent::CheckWinCondition();
}

struct METHOD_TYPE_GameAgent_DayPhase { };
template<> inline void GameAgent::_Execute_Method_<METHOD_TYPE_GameAgent_DayPhase>()
{
	this->GameAgent::DayPhase();
}

struct METHOD_TYPE_GameAgent_NightPhase { };
template<> inline void GameAgent::_Execute_Method_<METHOD_TYPE_GameAgent_NightPhase>()
{
	this->GameAgent::NightPhase();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
