// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "GameAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

GameAgent::GameAgent()
{
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

GameAgent::~GameAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

bool GameAgent::CheckWinCondition()
{
///<<< BEGIN WRITING YOUR CODE CheckWinCondition
    return false;
///<<< END WRITING YOUR CODE
}

void GameAgent::DayPhase()
{
///<<< BEGIN WRITING YOUR CODE DayPhase
///<<< END WRITING YOUR CODE
}

void GameAgent::NightPhase()
{
///<<< BEGIN WRITING YOUR CODE NightPhase
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
