// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_GAMEAGENT_H_
#define _BEHAVIAC_GAMEAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "player.h"

///<<< END WRITING YOUR CODE

class GameAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE GameAgent
///<<< END WRITING YOUR CODE
{
public:
	GameAgent();
	virtual ~GameAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(GameAgent, behaviac::Agent)

	private: bool CheckWinCondition();

	private: void DayPhase();

	private: void NightPhase();

///<<< BEGIN WRITING YOUR CODE CLASS_PART
public:
	std::vector<Player*> players;

    int dayCount = 1;

    void InitGame();
	void EndGame();
///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
